env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:import/recommended
  - google
  - next/core-web-vitals
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - import
  - '@typescript-eslint'
rules:
  require-jsdoc:
    - off
  sort-keys:
    - error
  sort-vars:
    - error
  '@typescript-eslint/explicit-function-return-type':
    - error
  import/first:
    - error
  import/newline-after-import:
    - error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      newlines-between: always
      alphabetize:
        order: asc
  react/jsx-sort-props:
    - error
  import/named:
    - off
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
